name: Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: protobuf

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run linter
        run: composer lint
