services:
  wiremock:
    image: wiremock/wiremock:3.13.1
    ports:
      - '18080:8080'
    volumes:
      - ./tests/E2E/OAuth2/mappings:/home/wiremock/mappings:ro
    healthcheck:
      test: ['CMD-SHELL', 'bash -c "echo >/dev/tcp/127.0.0.1/8080"']
      interval: 2s
      timeout: 3s
      retries: 30
