services:
  swoole:
    image: websocket-${PHP_VERSION:-8.3}-dev
    build:
      context: .
      dockerfile: php-${PHP_VERSION:-8.3}.Dockerfile
    command: php tests/servers/Swoole/server.php
    volumes:
      - ./src:/usr/src/code/src
      - ./tests:/usr/src/code/tests
      - ./phpunit.xml:/usr/src/code/phpunit.xml
    networks:
      - websockets
    ports:
      - "8001:80"
    healthcheck:
      test: ["CMD", "php", "-r", "exit(@fsockopen('127.0.0.1', 80) ? 0 : 1);"]
      interval: 2s
      timeout: 2s
      retries: 30

  workerman:
    image: websocket-${PHP_VERSION:-8.3}-dev
    build:
      context: .
      dockerfile: php-${PHP_VERSION:-8.3}.Dockerfile
    command: php tests/servers/Workerman/server.php start
    volumes:
      - ./src:/usr/src/code/src
      - ./tests:/usr/src/code/tests
      - ./phpunit.xml:/usr/src/code/phpunit.xml
    networks:
      - websockets
    ports:
      - "8002:80"
    healthcheck:
      test: ["CMD", "php", "-r", "exit(@fsockopen('127.0.0.1', 80) ? 0 : 1);"]
      interval: 2s
      timeout: 2s
      retries: 30

networks:
  websockets:
    driver: bridge
