<?php

declare(strict_types=1);

namespace Tests\Unit\Utopia\DNS;

use Exception;
use PHPUnit\Framework\TestCase;
use Utopia\DNS\Client;
use Utopia\DNS\Message;
use Utopia\DNS\Message\Question;
use Utopia\DNS\Message\Record;

final class ClientTest extends TestCase
{
    /** @var list<string> */
    private array $files = [];

    protected function tearDown(): void
    {
        foreach ($this->files as $file) {
            @unlink($file);
        }

        $this->files = [];
    }

    private function resolvConf(string $contents): string
    {
        $path = tempnam(sys_get_temp_dir(), 'resolv');

        if ($path === false) {
            $this->fail('Unable to create a temporary resolv.conf');
        }

        file_put_contents($path, $contents);
        $this->files[] = $path;

        return $path;
    }

    public function testReadsNameserversInFileOrder(): void
    {
        $path = $this->resolvConf(<<<'CONF'
            search cloud.svc.cluster.local svc.cluster.local
            nameserver 10.158.32.10
            nameserver 1.1.1.1
            options ndots:5
            CONF);

        $this->assertSame(['10.158.32.10', '1.1.1.1'], Client::systemNameservers($path));
    }

    public function testFromSystemSelectsTheFirstNameserver(): void
    {
        $path = $this->resolvConf("nameserver 10.158.32.10\nnameserver 1.1.1.1\n");

        $this->assertSame('10.158.32.10', Client::fromSystem($path)->getServer());
    }

    public function testIgnoresCommentsAndOtherDirectives(): void
    {
        $path = $this->resolvConf(<<<'CONF'
            # Generated by resolvconf
            ; nameserver 9.9.9.9
            domain example.com
            search example.com
            nameserver 8.8.8.8 # trailing comment
            sortlist 130.155.160.0/255.255.240.0
            options timeout:2 attempts:3
            CONF);

        $this->assertSame(['8.8.8.8'], Client::systemNameservers($path));
    }

    public function testAcceptsIpv6AndTabSeparatedNameservers(): void
    {
        $path = $this->resolvConf("nameserver\t2606:4700:4700::1111\nnameserver   8.8.4.4\n");

        $this->assertSame(['2606:4700:4700::1111', '8.8.4.4'], Client::systemNameservers($path));
    }

    /**
     * A UDP socket opened as AF_INET cannot address an IPv6 nameserver at all, so
     * the family has to follow the address the factory picked. Nothing listens on
     * the port, so the query still fails — but it has to fail on the read, which
     * only happens once the datagram has left.
     */
    public function testSendsToAnIpv6NameserverRatherThanFailingOnTheWrongFamily(): void
    {
        $probe = @socket_create(AF_INET6, SOCK_DGRAM, SOL_UDP);

        if ($probe === false || @socket_bind($probe, '::1', 0) === false) {
            $this->markTestSkipped('IPv6 loopback is unavailable on this host');
        }

        socket_getsockname($probe, $address, $port);
        socket_close($probe);

        $path = $this->resolvConf("nameserver ::1\n");
        $client = Client::fromSystem($path, $port, 1);

        $this->expectException(Exception::class);
        $this->expectExceptionMessageMatches('/Failed to receive data/');

        $client->query(Message::query(new Question('example.com', Record::TYPE_A)));
    }

    public function testSkipsMalformedAddressesButKeepsTheRest(): void
    {
        $path = $this->resolvConf(<<<'CONF'
            nameserver not-an-ip
            nameserver 999.999.999.999
            nameserver fe80::1%eth0
            nameserver 8.8.8.8
            CONF);

        $this->assertSame(['8.8.8.8'], Client::systemNameservers($path));
    }

    public function testDeduplicatesRepeatedNameservers(): void
    {
        $path = $this->resolvConf("nameserver 8.8.8.8\nnameserver 8.8.8.8\n");

        $this->assertSame(['8.8.8.8'], Client::systemNameservers($path));
    }

    public function testDoesNotTreatABareNameserverLineAsAnAddress(): void
    {
        $path = $this->resolvConf("nameserver\nnameserver 8.8.8.8 8.8.4.4\n");

        $this->assertSame([], Client::systemNameservers($path));
    }

    public function testReturnsNoNameserversWhenNoneAreDeclared(): void
    {
        $path = $this->resolvConf("search example.com\noptions ndots:5\n");

        $this->assertSame([], Client::systemNameservers($path));
    }

    public function testFromSystemFailsWhenNoNameserverIsDeclared(): void
    {
        $path = $this->resolvConf("search example.com\n");

        $this->expectException(Exception::class);
        $this->expectExceptionMessage("No nameserver found in {$path}.");

        Client::fromSystem($path);
    }

    public function testRereadsWhenTheFileIsRewritten(): void
    {
        $path = $this->resolvConf("nameserver 8.8.8.8\n");

        $this->assertSame(['8.8.8.8'], Client::systemNameservers($path));

        file_put_contents($path, "nameserver 10.158.32.10\nnameserver 1.1.1.1\n");

        $this->assertSame(['10.158.32.10', '1.1.1.1'], Client::systemNameservers($path));
    }

    /**
     * Two writes a second apart are indistinguishable by size alone, so the
     * modification time has to carry the difference.
     */
    public function testRereadsWhenOnlyTheModificationTimeChanges(): void
    {
        $path = $this->resolvConf("nameserver 8.8.8.8\n");

        $this->assertSame(['8.8.8.8'], Client::systemNameservers($path));

        file_put_contents($path, "nameserver 8.8.4.4\n"); // same byte length
        touch($path, time() + 10);

        $this->assertSame(['8.8.4.4'], Client::systemNameservers($path));
    }

    public function testCachesEachPathSeparately(): void
    {
        $first = $this->resolvConf("nameserver 8.8.8.8\n");
        $second = $this->resolvConf("nameserver 1.1.1.1\n");

        $this->assertSame(['8.8.8.8'], Client::systemNameservers($first));
        $this->assertSame(['1.1.1.1'], Client::systemNameservers($second));
        $this->assertSame(['8.8.8.8'], Client::systemNameservers($first));
    }

    public function testFailsAfterACachedFileIsRemoved(): void
    {
        $path = $this->resolvConf("nameserver 8.8.8.8\n");

        $this->assertSame(['8.8.8.8'], Client::systemNameservers($path));

        unlink($path);

        $this->expectException(Exception::class);
        $this->expectExceptionMessage("Unable to read {$path}.");

        Client::systemNameservers($path);
    }

    public function testFailsWhenTheFileCannotBeRead(): void
    {
        $path = sys_get_temp_dir() . '/utopia-dns-missing-resolv.conf';

        $this->expectException(Exception::class);
        $this->expectExceptionMessage("Unable to read {$path}.");

        Client::systemNameservers($path);
    }
}
