name: Debug

on:
  push:
    branches: [test-contract]

jobs:
  combos:
    strategy:
      fail-fast: false
      matrix:
        php: ['8.4', '8.5']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis, swoole
          coverage: none

      - name: Install
        run: composer update --no-interaction --no-progress --ignore-platform-reqs --working-dir packages/queue

      - name: Combos
        run: |
          cd packages/queue
          T=tests/Queue/E2E/Adapter
          run() { vendor/bin/phpunit $@ > /dev/null 2>&1; echo "[$*]: exit $?"; }
          run $T/LockingTest.php $T/SwooleConcurrencyTest.php
          run $T/ServerTelemetryTest.php $T/SwooleConcurrencyTest.php
          run $T/LockingTest.php $T/ServerTelemetryTest.php
          run $T/RedisReconnectCallbackTest.php $T/SwooleConcurrencyTest.php
          run $T/LockingTest.php $T/RedisReconnectCallbackTest.php $T/ServerTelemetryTest.php $T/SwooleConcurrencyTest.php
